<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      async function async1() {
        console.log(1);
        await async2();
        console.log(2);
        return 3;
      }

      async function async2() {
        console.log(4);
      }

      console.log(5);

      setTimeout(() => console.log(6), 0);

      async1().then((message) => console.log(message));

      new Promise((resolve) => {
        console.log(7);
        resolve();
      }).then(() => console.log(8));

      setTimeout(() => console.log(10));

      console.log(9);

      // 第一步
      // 5 1 4 7 9
      // 宏任务队列 setTimeout6 setTimeout10
      // 微任务队列 ( 2 3 ) 8
      // - 注意：这里的 23 是一个整体的微任务

      // 第二步
      // 2 8
      // 微任务队列 3，正好还在遍历微任务过程中，所以 3 也会在本轮被遍历
      // 2 8 3

      // 总 51479 283 610

      // 资料：https://segmentfault.com/a/1190000015057278
    </script>
  </body>
</html>
